udate

diff --git a/build-push copy.yaml b/build-push copy.yaml
--- a/build-push copy.yaml
+++ b/build-push copy.yaml
@@ -119,4 +119,110 @@ spec:
     name: tag-release
     resources: {}
     workingDir: $(inputs.resources.source.path)
+  - args:
+    - -c
+    - |
+      set -e
 
+      . ./env-config
+
+      IMAGE_URL=$(outputs.resources.image.url)
+
+      REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
+      REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
+
+      APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}"
+
+      buildah bud --tls-verify=$(inputs.params.TLSVERIFY) --format=docker -f $(inputs.params.DOCKERFILE) -t ${APP_IMAGE}  $(inputs.params.CONTEXT)
+      if [[ -n "${REGISTRY_USER}" ]] && [[ -n "${REGISTRY_PASSWORD}" ]]; then
+        buildah login -u "${REGISTRY_USER}" -p "${REGISTRY_PASSWORD}" "${REGISTRY_URL}"
+      fi
+      buildah push --tls-verify=$(inputs.params.TLSVERIFY) "${APP_IMAGE}" "docker://${APP_IMAGE}"
+    command:
+    - /bin/bash
+    env:
+    - name: REGISTRY_USER
+      valueFrom:
+        secretKeyRef:
+          key: REGISTRY_USER
+          name: ibmcloud-apikey
+          optional: true
+    - name: REGISTRY_PASSWORD
+      valueFrom:
+        secretKeyRef:
+          key: APIKEY
+          name: ibmcloud-apikey
+          optional: true
+    image: $(inputs.params.BUILDER_IMAGE)
+    name: build
+    resources: {}
+    securityContext:
+      privileged: true
+    volumeMounts:
+    - mountPath: /var/lib/containers
+      name: varlibcontainers
+    workingDir: $(inputs.resources.source.path)
+  - args:
+      - -c
+      - |
+        set -e
+  
+        . ./env-config
+  
+        IMAGE_URL=$(outputs.resources.image.url)
+  
+        REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
+        REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
+  
+        APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}"
+  
+        export TRIVY_AUTH_URL=${REGISTRY_URL}
+        export TRIVY_USERNAME=${REGISTRY_USER}
+        export TRIVY_PASSWORD=${REGISTRY_PASSWORD}
+
+        echo "ScanImage Before Trivy image scanning.... $APP_IMAGE"
+
+        # Trivy scan
+        trivy ${APP_IMAGE}
+        # trivy --exit-code 1 --severity CRITICAL ${APP_IMAGE}
+
+        # Trivy scan result processing
+        my_exit_code=$?
+        echo "RESULT 1:--- $my_exit_code"
+
+        # Check scan results
+        if [ ${my_exit_code} == 1 ]; then
+            echo "Image scanning failed. Some vulnerabilities found"
+            exit 1;
+        else
+            echo "Image is scanned Successfully. No vulnerabilities found"
+        fi;
+
+        echo "ScanImage After Trivy image scanning....0"
+    command:
+      - /bin/sh
+      env:
+      - name: REGISTRY_USER
+        valueFrom:
+          secretKeyRef:
+            key: REGISTRY_USER
+            name: ibmcloud-apikey
+            optional: true
+      - name: REGISTRY_PASSWORD
+        valueFrom:
+          secretKeyRef:
+            key: APIKEY
+            name: ibmcloud-apikey
+            optional: true
+      image: $(inputs.params.BUILDER_IMAGE)
+      name: build
+      resources: {}
+      securityContext:
+        privileged: true
+      volumeMounts:
+      - mountPath: /var/lib/containers
+        name: varlibcontainers
+      workingDir: $(inputs.resources.source.path)
+  volumes:
+  - emptyDir: {}
+    name: varlibcontainers
diff --git a/igc-build-tag-push.yaml b/igc-build-tag-push.yaml
--- a/igc-build-tag-push.yaml
+++ b/igc-build-tag-push.yaml
@@ -14,7 +14,7 @@ spec:
       type: string
     - default: docker.io/aquasec/trivy
       name: trivy
-      type: string
+      type: string      
     - default: ./Dockerfile
       name: DOCKERFILE
       type: string
@@ -37,29 +37,22 @@ spec:
     - |
       set -e
 
-      echo "Test 1  1 --->"
-
-
       if [[ -z "$GIT_AUTH_USER" ]] || [[ -z "$GIT_AUTH_PWD" ]]; then
         echo "Git credentials not found. The pipeline expects to find them in a secret named 'git-credentials'."
         echo "  Update your CLI and register the pipeline again"
         exit 1
       fi
-      echo "Test 1  2 --->"
 
       echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
       git fetch --unshallow
       git fetch --tags
       git tag -l
-      echo "Test 1  3 --->"
 
       git checkout ${BRANCH}
       git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
-      echo "Test 1  4 --->"
 
       git config --global user.email "cloud-native-toolkit@example.com"
       git config --global user.name "Cloud Native Toolkit Pipeline"
-      echo "Test 1  5 --->"
 
       if [[ "${BRANCH}" == "master" ]] && [[ $(git describe --tag `git rev-parse HEAD`) =~ (^[0-9]+.[0-9]+.[0-9]+$) ]] || \
          [[ $(git describe --tag `git rev-parse HEAD`) =~ (^[0-9]+.[0-9]+.[0-9]+-${BRANCH}[.][0-9]+$) ]]
@@ -69,18 +62,15 @@ spec:
           echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" >> ./env-config
           exit 0
       fi
-      echo "Test 1  6 --->"
 
       mkdir -p ~/.npm
       npm config set prefix ~/.npm
       export PATH=$PATH:~/.npm/bin
       npm i -g release-it
-      echo "Test 1  7 --->"
 
       if [[ "${BRANCH}" != "master" ]]; then
           PRE_RELEASE="--preRelease=${BRANCH}"
       fi
-      echo "Test 1  8 --->"
 
 
       release-it patch ${PRE_RELEASE} \
@@ -95,21 +85,16 @@ spec:
 
       echo "IMAGE_VERSION=$(git describe --abbrev=0 --tags)" > ./env-config
       echo "IMAGE_NAME=$(basename -s .git `git config --get remote.origin.url` | tr '[:upper:]' '[:lower:]' | sed 's/_/-/g')" >> ./env-config
-      echo "Test 1  9 --->"
 
       source ./env-config
       if [[ -z "${IMAGE_VERSION}" ]]; then
           echo "Error: IMAGE_VERSION not defined"
           exit 1
       fi
-      echo "Test 1  10 --->"
-
       if [[ -z "${IMAGE_NAME}" ]]; then
           echo "Error: IMAGE_NAME not defined"
           exit 1
       fi
-      echo "Test 1  11 --->"
-
     command:
     - /bin/bash
     env:
@@ -135,26 +120,20 @@ spec:
     - -c
     - |
       set -e
-      echo "Test 2  1 --->"
 
       . ./env-config
 
       IMAGE_URL=$(outputs.resources.image.url)
-      echo "Test 2  2 --->"
 
       REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
       REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
-      echo "Test 2  3 --->"
 
-      APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}-temp:${IMAGE_VERSION}"
-      echo "Test 2  4 --->"
+      APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}"
 
       buildah bud --tls-verify=$(inputs.params.TLSVERIFY) --format=docker -f $(inputs.params.DOCKERFILE) -t ${APP_IMAGE}  $(inputs.params.CONTEXT)
       if [[ -n "${REGISTRY_USER}" ]] && [[ -n "${REGISTRY_PASSWORD}" ]]; then
         buildah login -u "${REGISTRY_USER}" -p "${REGISTRY_PASSWORD}" "${REGISTRY_URL}"
       fi
-      echo "Test 2  5 --->"
-
       buildah push --tls-verify=$(inputs.params.TLSVERIFY) "${APP_IMAGE}" "docker://${APP_IMAGE}"
     command:
     - /bin/bash
@@ -181,122 +160,112 @@ spec:
       name: varlibcontainers
     workingDir: $(inputs.resources.source.path)
   - args:
-      - -c
-      - |
-        set -e
-        echo "Test 3  1 --->"
-        . ./env-config
+    - -c
+    - |
+      set -e
 
-        IMAGE_URL=$(outputs.resources.image.url)
+      . ./env-config
 
-        REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
-        REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
+      IMAGE_URL=$(outputs.resources.image.url)
 
-        APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}-temp:${IMAGE_VERSION}"
+      REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
+      REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
 
-        export TRIVY_AUTH_URL=${REGISTRY_URL}
-        export TRIVY_USERNAME=${REGISTRY_USER}
-        export TRIVY_PASSWORD=${REGISTRY_PASSWORD}
+      APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}-temp:${IMAGE_VERSION}"
 
-        echo "ScanImage Before Trivy image scanning.... $APP_IMAGE"
+      export TRIVY_AUTH_URL=${REGISTRY_URL}
+      export TRIVY_USERNAME=${REGISTRY_USER}
+      export TRIVY_PASSWORD=${REGISTRY_PASSWORD}
 
-        # Trivy scan
-        trivy ${APP_IMAGE}
-        # trivy --exit-code 1 --severity CRITICAL ${APP_IMAGE}
+      echo "Trivy image scanning.... $APP_IMAGE"
 
-        # Trivy scan result processing
-        my_exit_code=$?
-        echo "RESULT 1:--- $my_exit_code"
+      # Trivy scan
+      trivy ${APP_IMAGE}
+      # trivy --exit-code 1 --severity CRITICAL ${APP_IMAGE}
 
-        # Check scan results
-        if [ ${my_exit_code} == 1 ]; then
-            echo "Image scanning failed. Some vulnerabilities found"
-            exit 1;
-        else
-            echo "Image is scanned Successfully. No vulnerabilities found"
-        fi;
+      # Trivy scan result processing
+      my_exit_code=$?
+      echo "RESULT 1:--- $my_exit_code"
 
-        echo "ScanImage After Trivy image scanning....0"
-      command:
-      - /bin/sh
-      env:
-      - name: REGISTRY_USER
-        valueFrom:
-          secretKeyRef:
-            key: REGISTRY_USER
-            name: ibmcloud-apikey
-            optional: true
-      - name: REGISTRY_PASSWORD
-        valueFrom:
-          secretKeyRef:
-            key: APIKEY
-            name: ibmcloud-apikey
-            optional: true
-      image: $(inputs.params.trivy)
-      name: image-scan
-      resources: {}
-      securityContext:
-        privileged: true
-      volumeMounts:
-      - mountPath: /var/lib/containers
-        name: varlibcontainers
-      workingDir: $(inputs.resources.source.path)
-    - args:
-      - -c
-      - |
-        set -e
-        echo "Test 4  1 --->"
+      # Check scan results
+      if [ ${my_exit_code} == 1 ]; then
+          echo "Image scanning failed. Some vulnerabilities found"
+          exit 1;
+      else
+          echo "Image is scanned Successfully. No vulnerabilities found"
+      fi;
+    command:
+    - /bin/bash
+    env:
+    - name: REGISTRY_USER
+      valueFrom:
+        secretKeyRef:
+          key: REGISTRY_USER
+          name: ibmcloud-apikey
+          optional: true
+    - name: REGISTRY_PASSWORD
+      valueFrom:
+        secretKeyRef:
+          key: APIKEY
+          name: ibmcloud-apikey
+          optional: true
+    image: $(inputs.params.trivy)
+    name: image-scan
+    resources: {}
+    securityContext:
+      privileged: true
+    volumeMounts:
+    - mountPath: /var/lib/containers
+      name: varlibcontainers
+    workingDir: $(inputs.resources.source.path)
+  - args:
+    - -c
+    - |
+      set -e
 
-        . ./env-config
+      . ./env-config
 
-        IMAGE_URL=$(outputs.resources.image.url)
-        echo "Test 4  2 --->"
+      IMAGE_URL=$(outputs.resources.image.url)
 
-        REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
-        REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
-        echo "Test 4  3 --->"
+      REGISTRY_URL=$(echo $IMAGE_URL | awk -F / '{print $1}')
+      REGISTRY_NAMESPACE=$(echo $IMAGE_URL | awk -F / '{print $2}')
 
-        APP_IMAGE_Temp="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}-temp:${IMAGE_VERSION}"
-        APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}"
+      APP_IMAGE="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}:${IMAGE_VERSION}"
+      APP_IMAGE_Temp="${REGISTRY_URL}/${REGISTRY_NAMESPACE}/${IMAGE_NAME}-temp:${IMAGE_VERSION}"
 
-        echo "Test 4  4 --->"
-
-        buildah bud --tls-verify=$(inputs.params.TLSVERIFY) --format=docker -f $(inputs.params.DOCKERFILE) -t ${APP_IMAGE}  $(inputs.params.CONTEXT)
-        if [[ -n "${REGISTRY_USER}" ]] && [[ -n "${REGISTRY_PASSWORD}" ]]; then
+      if [[ -n "${REGISTRY_USER}" ]] && [[ -n "${REGISTRY_PASSWORD}" ]]; then
           buildah login -u "${REGISTRY_USER}" -p "${REGISTRY_PASSWORD}" "${REGISTRY_URL}"
-        fi
-        echo "Test 4  5 --->"
+      fi
 
-        buildah pull ${APP_IMAGE_Temp}
-        buildah tag ${APP_IMAGE_Temp} ${APP_IMAGE}
-        buildah push --tls-verify=${TLSVERIFY} "${APP_IMAGE}" "docker://${APP_IMAGE}"
-        buildah rmi ${APP_IMAGE_Temp}
+      buildah pull ${APP_IMAGE_Temp}
+      buildah tag ${APP_IMAGE_Temp} ${APP_IMAGE}
+      buildah push --tls-verify=${TLSVERIFY} "${APP_IMAGE}" "docker://${APP_IMAGE}"
+      buildah rmi ${APP_IMAGE_Temp}
 
-        #buildah push --tls-verify=$(inputs.params.TLSVERIFY) "${APP_IMAGE}" "docker://${APP_IMAGE}"
-      command:
-      - /bin/bash
-      env:
-      - name: REGISTRY_USER
-        valueFrom:
-          secretKeyRef:
-            key: REGISTRY_USER
-            name: ibmcloud-apikey
-            optional: true
-          - name: REGISTRY_PASSWORD
-            valueFrom:
-              secretKeyRef:
-                key: APIKEY
-                name: ibmcloud-apikey
-                optional: true
-      image: $(inputs.params.BUILDER_IMAGE)
-      name: push
-      resources: {}
-      securityContext:
-        privileged: true
-      volumeMounts:
-      - mountPath: /var/lib/containers
-        name: varlibcontainers
-      workingDir: $(inputs.resources.source.path)
+    command:
+    - /bin/bash
+    env:
+    - name: REGISTRY_USER
+      valueFrom:
+        secretKeyRef:
+          key: REGISTRY_USER
+          name: ibmcloud-apikey
+          optional: true
+    - name: REGISTRY_PASSWORD
+      valueFrom:
+        secretKeyRef:
+          key: APIKEY
+          name: ibmcloud-apikey
+          optional: true
+    image: $(inputs.params.BUILDER_IMAGE)
+    name: push
+    resources: {}
+    securityContext:
+      privileged: true
+    volumeMounts:
+    - mountPath: /var/lib/containers
+      name: varlibcontainers
+    workingDir: $(inputs.resources.source.path)
   volumes:
   - emptyDir: {}
     name: varlibcontainers
